"use client";

import { useEffect, useState } from "react";
import {
  TripLayoutConfig,
  TripSummaryBlockId,
  DEFAULT_TRIP_LAYOUT_VISIBILITY,
  DEFAULT_TRIP_LAYOUT_SEQUENCE
} from "@/lib/trip-layout";

type SaveState = "idle" | "saving" | "saved" | "error";

type BlockMeta = {
  id: TripSummaryBlockId;
  title: string;
  description: string;
  canHide: boolean;
};

const BLOCKS: BlockMeta[] = [
  {
    id: "tripFinances",
    title: "Trip Finances",
    description: "Totals, paid amounts, and remaining balance for this trip.",
    canHide: true
  },
  {
    id: "regenerate",
    title: "Regenerate Itinerary",
    description: "Server-side AI re-generation controls for the itinerary.",
    canHide: false
  },
  {
    id: "notes",
    title: "Notes & Tips",
    description: "Optional notes generated by AI or entered by travelers.",
    canHide: false
  },
  {
    id: "bookings",
    title: "Bookings",
    description: "List of individual bookings and quick-add form.",
    canHide: true
  },
  {
    id: "vendorQuotes",
    title: "Vendor Quotes",
    description: "Access to vendor quotes linked to the trip.",
    canHide: false
  }
];

function orderBlocks(sequence: TripSummaryBlockId[]): BlockMeta[] {
  const byId = new Map<TripSummaryBlockId, BlockMeta>();
  for (const meta of BLOCKS) byId.set(meta.id, meta);
  const result: BlockMeta[] = [];
  for (const id of sequence) {
    const meta = byId.get(id);
    if (meta) result.push(meta);
  }
  return result;
}

export function TripLayoutSettings() {
  const [version, setVersion] = useState<number | null>(null);
  const [sequence, setSequence] = useState<TripSummaryBlockId[]>([...
    DEFAULT_TRIP_LAYOUT_SEQUENCE
  ]);
  const [visibility, setVisibility] = useState(DEFAULT_TRIP_LAYOUT_VISIBILITY);
  const [loading, setLoading] = useState(true);
  const [saveState, setSaveState] = useState<SaveState>("idle");
  const [error, setError] = useState<string | null>(null);
  const [draggingId, setDraggingId] = useState<TripSummaryBlockId | null>(null);
  const [hasChanges, setHasChanges] = useState(false);

  useEffect(() => {
    let cancelled = false;
    async function load() {
      try {
        const res = await fetch("/api/admin/trip-layout", { cache: "no-store" });
        let data: any = null;
        try {
          data = await res.json();
        } catch {
          data = null;
        }
        if (!res.ok) {
          throw new Error(data?.message || "Failed to load trip layout");
        }
        if (!cancelled && data?.ok && data.config) {
          const cfg: TripLayoutConfig = data.config;
          setVersion(cfg.version);
          setSequence(cfg.sequence);
          setVisibility(cfg.visibility);
          setHasChanges(false);
        }
      } catch (e: any) {
        if (!cancelled) {
          setError(e?.message || "Failed to load trip layout");
        }
      } finally {
        if (!cancelled) setLoading(false);
      }
    }
    load();
    return () => {
      cancelled = true;
    };
  }, []);

  function markChanged() {
    setHasChanges(true);
    setSaveState("idle");
    setError(null);
  }

  function handleToggle(id: TripSummaryBlockId) {
    if (id !== "tripFinances" && id !== "bookings") return;
    setVisibility((prev) => {
      const next = { ...prev, [id]: !prev[id] } as typeof prev;
      return next;
    });
    markChanged();
  }

  function handleDragStart(id: TripSummaryBlockId) {
    setDraggingId(id);
  }

  function handleDrop(targetId: TripSummaryBlockId) {
    setSequence((prev) => {
      if (!draggingId || draggingId === targetId) return prev;
      const current = [...prev];
      const fromIndex = current.indexOf(draggingId);
      const toIndex = current.indexOf(targetId);
      if (fromIndex === -1 || toIndex === -1) return prev;
      current.splice(fromIndex, 1);
      current.splice(toIndex, 0, draggingId);
      return current;
    });
    setDraggingId(null);
    markChanged();
  }

  async function save(resetToDefault = false) {
    setSaveState("saving");
    setError(null);
    try {
      const res = await fetch("/api/admin/trip-layout", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          version,
          visibility: resetToDefault ? undefined : visibility,
          sequence: resetToDefault ? undefined : sequence,
          resetToDefault
        })
      });

      const data = await res.json();

      if (res.status === 409 && data?.config) {
        const cfg: TripLayoutConfig = data.config;
        setVersion(cfg.version);
        setSequence(cfg.sequence);
        setVisibility(cfg.visibility);
        setHasChanges(false);
        setSaveState("error");
        setError(
          data?.message ||
            "Trip layout was updated by another administrator. Changes were not saved."
        );
        return;
      }

      if (!res.ok || !data?.ok) {
        throw new Error(data?.message || "Failed to save trip layout");
      }

      const cfg: TripLayoutConfig = data.config;
      setVersion(cfg.version);
      setSequence(cfg.sequence);
      setVisibility(cfg.visibility);
      setHasChanges(false);
      setSaveState("saved");
    } catch (e: any) {
      setSaveState("error");
      setError(e?.message || "Failed to save trip layout");
    }
  }

  const orderedBlocks = orderBlocks(sequence);
  const linkSettings = visibility.itineraryLinks;

  const itineraryLinkOptions = [
    {
      key: "showDirections" as const,
      title: "Directions link",
      description: "Show a quick directions link when coordinates are available."
    },
    {
      key: "showMap" as const,
      title: "Map link",
      description: "Show a map search link when only a place name is available."
    },
    {
      key: "showMoreInfo" as const,
      title: "More info link",
      description: "Show an additional web search link for more information."
    }
  ];

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div className="space-y-1">
          <p className="text-sm text-neutral-300">
            Configure visibility and ordering of blocks in the Trip Summary
            section.
          </p>
          <p className="text-xs text-neutral-500">
            Changes apply globally to all trips once saved.
          </p>
        </div>
        <div className="flex items-center gap-2">
          {hasChanges ? (
            <span className="rounded-full bg-amber-500/10 px-3 py-1 text-xs font-medium text-amber-300">
              Unsaved changes
            </span>
          ) : (
            <span className="rounded-full bg-emerald-500/10 px-3 py-1 text-xs font-medium text-emerald-300">
              Saved
            </span>
          )}
        </div>
      </div>

      {error && (
        <div className="rounded border border-red-800 bg-red-950 px-3 py-2 text-xs text-red-200">
          {error}
        </div>
      )}

      {loading ? (
        <div className="rounded-xl border border-neutral-800 bg-neutral-900 p-6 text-sm text-neutral-400">
          Loading trip layout preferences...
        </div>
      ) : (
        <>
          <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
            <div className="space-y-3">
              <h2 className="text-sm font-semibold text-neutral-200">Block sequence</h2>
              <p className="text-xs text-neutral-500">
                Drag and drop blocks to change their order.
              </p>
              <div className="space-y-2">
                {orderedBlocks.map((block, idx) => (
                  <div
                    key={block.id}
                    draggable
                    onDragStart={() => handleDragStart(block.id)}
                    onDragOver={(e) => e.preventDefault()}
                    onDrop={() => handleDrop(block.id)}
                    className="flex cursor-move items-center justify-between rounded border border-neutral-800 bg-neutral-900 px-3 py-2 text-sm text-neutral-100 hover:border-neutral-700"
                  >
                    <div className="flex items-center gap-3">
                      <span className="flex h-6 w-6 items-center justify-center rounded-full bg-neutral-800 text-xs text-neutral-300">
                        {idx + 1}
                      </span>
                      <div>
                        <div className="font-medium">{block.title}</div>
                        <div className="text-xs text-neutral-500">
                          {block.description}
                        </div>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            <div className="space-y-3">
              <h2 className="text-sm font-semibold text-neutral-200">Visibility controls</h2>
              <p className="text-xs text-neutral-500">
                Hide or show specific blocks in the Trip Summary section.
              </p>
              <div className="space-y-2">
                {orderedBlocks.map((block) => {
                  const isVisible =
                    block.id === "tripFinances"
                      ? visibility.tripFinances
                      : block.id === "bookings"
                      ? visibility.bookings
                      : true;

                  return (
                    <div
                      key={block.id}
                      className="flex items-center justify-between rounded border border-neutral-800 bg-neutral-900 px-3 py-2 text-sm text-neutral-100"
                    >
                      <div>
                        <div className="font-medium">{block.title}</div>
                        <div className="text-xs text-neutral-500">
                          {block.canHide
                            ? "Toggle visibility for all users."
                            : "Always visible. Cannot be hidden."}
                        </div>
                      </div>
                      {block.canHide ? (
                        <button
                          type="button"
                          onClick={() => handleToggle(block.id)}
                          className={`relative inline-flex h-6 w-11 items-center rounded-full border text-xs transition-colors ${
                            isVisible
                              ? "border-emerald-500 bg-emerald-600"
                              : "border-neutral-700 bg-neutral-800"
                          }`}
                        >
                          <span
                            className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${
                              isVisible ? "translate-x-5" : "translate-x-1"
                            }`}
                          />
                        </button>
                      ) : (
                        <span className="text-xs text-neutral-500">Always on</span>
                      )}
                    </div>
                  );
                })}
              </div>

              <div className="mt-6 space-y-2">
                <h3 className="text-xs font-semibold uppercase tracking-wide text-neutral-400">
                  Itinerary link density
                </h3>
                <p className="text-xs text-neutral-500">
                  Control which external links appear on each activity card.
                </p>
                <div className="mt-2 space-y-2">
                  {itineraryLinkOptions.map((opt) => {
                    const enabled = linkSettings[opt.key];
                    return (
                      <div
                        key={opt.key}
                        className="flex items-center justify-between rounded border border-neutral-800 bg-neutral-900 px-3 py-2 text-sm text-neutral-100"
                      >
                        <div>
                          <div className="font-medium">{opt.title}</div>
                          <div className="text-xs text-neutral-500">{opt.description}</div>
                        </div>
                        <button
                          type="button"
                          onClick={() => {
                            setVisibility((prev) => ({
                              ...prev,
                              itineraryLinks: {
                                ...prev.itineraryLinks,
                                [opt.key]: !prev.itineraryLinks[opt.key]
                              }
                            }));
                            markChanged();
                          }}
                          className={`relative inline-flex h-6 w-11 items-center rounded-full border text-xs transition-colors ${
                            enabled
                              ? "border-emerald-500 bg-emerald-600"
                              : "border-neutral-700 bg-neutral-800"
                          }`}
                        >
                          <span
                            className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${
                              enabled ? "translate-x-5" : "translate-x-1"
                            }`}
                          />
                        </button>
                      </div>
                    );
                  })}
                </div>
              </div>
            </div>
          </div>

          <div className="flex flex-wrap items-center justify-between gap-3 border-t border-neutral-800 pt-4">
            <div className="text-xs text-neutral-500">
              Version {version ?? 1}. Use reset to restore default ordering and
              visibility.
            </div>
            <div className="flex items-center gap-2">
              <button
                type="button"
                onClick={() => save(true)}
                className="rounded border border-neutral-700 px-3 py-2 text-xs font-medium text-neutral-200 hover:bg-neutral-800"
                disabled={saveState === "saving"}
              >
                Reset to defaults
              </button>
              <button
                type="button"
                onClick={() => save(false)}
                className="rounded bg-indigo-600 px-4 py-2 text-xs font-semibold text-white hover:bg-indigo-500 disabled:opacity-60"
                disabled={!hasChanges || saveState === "saving"}
              >
                {saveState === "saving" ? "Saving..." : "Save changes"}
              </button>
            </div>
          </div>
        </>
      )}
    </div>
  );
}

